apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: priporocanjeprofilov-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: priporocanjeProfilov
    spec:
      containers:
      - image: tjasaj/priporocanje-profilov:0.01
        name: priporocanje-profilov
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP